### ISSUE TITLE
Enigmatic graves duplicating items when a Relics belt is equipped

### ISSUE THREAD

**Issue by Vaerys-Dawn** [Quarris/EnigmaticGraves#27]
Steps to reproduce:
- Die with a relics belt item equipped in your curio slot
- Find the grave with the grave finder
- right-click the grave
- right-click the grave again

proof of bug occurring: ![2021-11-06_06-08-57](https://user-images.githubusercontent.com/5305116/140565667-f00cec1c-ee85-4618-b971-3ccc09d83704.gif)

Versions
Forge: 1.6.5-46.2.0
EnigmaticGraves: 1.6.3
CuriosApi: 1.16.5-4.0.5.3
Relics: 0.3.1

**Comment by Quarris** [comment]
That's odd, the grave shouldn't stay after you restored it once, does the grave act normally when you don't have relics on?

**Comment by Quarris** [comment]
Found the issue, the quick solution I have right now is that the talismans will not be replaced into the curios and just placed into the main inv.
This is because the belt adds new slots, so any items in the new slots cannot be added back because when the items are restored, the new slots don't get added until later.
