### ISSUE TITLE
enigmatic graves disappearing.

### ISSUE THREAD

**Issue by opticGT** [Quarris/EnigmaticGraves#37]
i kept dying and doing /back like 10 or so times. in the atum pyramid and and i pick up my graves. but im missing a grave but still have a  grave finder 
![2022-04-14_00 36 31](https://user-images.githubusercontent.com/19476801/163329512-69e4ecb3-fb83-4dee-a6bb-c3ad58ee377c.png)
![2022-04-14_00 36 27](https://user-images.githubusercontent.com/19476801/163329528-651028cd-faf8-472c-9b9d-8a5df55a505a.png)

**Comment by Quarris** [comment]
What mod version?

Is this on server, do you have access to debug log for this instance?

**Comment by DamienTC** [comment]
i am on a server and i dont know what a debug log is

**Comment by Quarris** [comment]
And which mod version?

**Comment by DamienTC** [comment]
looks like 1.7.4

**Comment by DamienTC** [comment]
latest version on e6e

**Comment by Quarris** [comment]
I assume you're not the server owner. If you're able to ask someone who has access to the server files to provide logs from the day that this happened that'd be great, otherwise E6E is currently running older version of the mod, which the newer one might fix this.

I don't have enough info right now to see where the problem is. The admins might be able to recover your items with commands if you ask them
